### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by maferincon** [sabas1080/TembooForESP8266#1]
Hola Sabas1080!!
He estado buscando como utilizar temboo con el ESP8266, he visto que implementas un codigo..
Tu utilizas solo el ESP o tambien un arduino?
Te agradezco que me puedas ayudar!

**Comment by sabas1080** [comment]
Hola @maferincon 

Esta versión es para utilizar en el con el plugin de Arduino IDE y programar directamente el ESP

Saludos
