### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by bphermansson** [sabas1080/TembooForESP8266#2]
How do I tell the Ide to use this lib instead of the built in Temboo-lib? 
I use this code: 

```
#include <Temboo.h>
#include "TembooAccount.h" // Contains Temboo account information
```
and the compiler answer:
```
/media/patrik/1TB_2014/patrik/Program/arduino-1.8.1/libraries/Temboo/src/Temboo.cpp:38:26: fatal error: avr/pgmspace.h: No such file or directory
 #include <avr/pgmspace.h>
                          ^
compilation terminated.
Using library Temboo at version 1.1.8 in folder: /media/patrik/1TB_2014/patrik/Program/arduino-1.8.1/libraries/Temboo 
```

and :
`
Invalid library found in /media/nasFiler/Programmering/Arduino/sketchbook/libraries/TembooForESP8266: /media/nasFiler/Programmering/Arduino/sketchbook/libraries/TembooForESP8266`

**Comment by sabas1080** [comment]
Hi @bphermansson 
Replace your current "arduino-1.8.1/libraries/Temboo/" library with the contents of TembooESP8266

**Comment by bphermansson** [comment]
Hi @sabas1080 :)
Thanks for a quick answer! When I do as you suggest I get:
```
In file included from /media/nasFiler/Programmering/Arduino/sketchbook/temp/sketch_jan25a/sketch_jan25a.ino:1:0:
/media/patrik/1TB_2014/patrik/Program/arduino-1.8.1/libraries/Temboo/src/Temboo.h:65:37: fatal error: utility/ChoreoOutputSet.h: No such file or directory
 #include "utility/ChoreoOutputSet.h"
```

**Comment by bphermansson** [comment]
Sorry my mistake... I replaced the whole folder, not the contents. The trick is to overwrite the content in the Temboo folder with the content in TembooESP8266 zip.

**Comment by bphermansson** [comment]
Tried it again and it wont compile. Used this simple test code:
```

#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <Temboo.h>       
void setup() {
}
void loop() {
}
```

And the result:

`xtensa-lx106-elf-gcc: error: /tmp/arduino_build_779746/libraries/Bridge/Bridge.a: No such file or directory`

**Comment by sabas1080** [comment]
Try to follow this tutorial and delete past folder from Temboo
https://learn.adafruit.com/adafruit-all-about-arduino-libraries-install-use/arduino-libraries

**Comment by uditk14** [comment]
Can we use Arduino Uno+ESP8266 for this?? While selecting the board, i m getting error when selecting UNO but not when selecting YUN

**Comment by sabas1080** [comment]
@uditk14 Arduino+ESP8266(Mode AT)

https://github.com/bportaluri/WiFiEsp + it library temboo
